#!/usr/bin/env bash
# Bash script that configur a new Ubuntu machine
# respect above requirements
# script will be run on the server itself

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# starting the nginx service
sudo service nginx start

# allowing nginx on the firewall
sudo ufw allow 'Nginx HTTP'

# Give user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup a  default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating a new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restarting the nginx
sudo service nginx restart

echo -e "\nCompleted. ✅\n"
