#!/usr/bin/env bash
# script that pings an IP address passed as an argument

#var
IP=${1}

# file name
file=$(basename "${BASH_SOURCE[@]}")

# if 
if ! [ "$IP" ]; then
	echo "Usage: ${file} {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
fi
