#!/usr/bin/env bash
# function to print script to using while loop and thn 9 iteration print hi

x=1

while [ $x -lt 11 ]; do
	echo "Best School"

	#if statement to print HI in 9 itertion
	if [ $x -eq 9 ]; then
		echo "Hi"
	fi

	((x++))
done	
