#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes

hours=0

while [ $hours -lt 12 ]; do
	echo "hours: $hours"

	min=1

	while [ $min -lt 60 ]; do
		echo "$min"
		((min++))
	done

	((hours++))
done
