#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash

file="school"

#check file exists
if [ -e $file ]; then
	echo "school file exists"

	# check file empty
	if [ ! -s $file ]; then
		echo "school file is empty"

		# checks file is a regular file
		if [ -f "$file" ]; then
			echo "school is a regular file"
		fi

	else
		echo "school file is not empty"

		# checks if file is a regular file
		if [ -f $file ]; then
			echo "school is a regular file"
		fi
	fi

else
	echo "school file does not exist"
fi

